#!/bin/bash
docker build -t docker-camera/base ./base
docker build -t docker-camera/motion ./motion
docker run -e \
        POSTGRES_DB=postgres \
        POSTGRES_USER=beo \
        POSTGRES_PASSWORD=beo \
        -p 5432:5432 \
        --volume=home/pirate/docker-camera/data/postgres:/var/lib/postgresql/data \
        -d postgres && \
docker run -dit \
        --restart always \
        --device=/dev/video0:/dev/video0 \
        --device=/dev/video1:/dev/video1 \
        -p 8090:8090 \
        -p 8080:8080 \
        -p 8081:8081 \
        -p 8082:8082 \
        -p 8083:8083 \
        -p 8084:8084 \
        --volume=/home/pirate/docker-camera/log:/var/log \
        docker-camera/motion
