#!/bin/bash
docker build -t docker-camera/base ./base
#docker build -t docker-camera/motion ./motion
docker build -t docker-camera/java ./java
docker build -t docker-camera/front ./front
docker run \
        -e POSTGRES_DB=postgres \
        -e POSTGRES_USER=beo \
        -e POSTGRES_PASSWORD=beo \
        --network host \
        --volume=/home/pirate/docker-camera/data/postgres:/var/lib/postgresql/data \
        --name camera-postgresql \
        -d tobi312/rpi-postgresql && \
docker run -dit \
        --restart always \
        --network host \
        --name camera-rabbit \
        rabbitmq:3-management && \
docker exec camera-rabbit rabbitmq-plugins enable rabbitmq_web_stomp && \
# docker run -dit \
#         --restart always \
#         --device=/dev/video0:/dev/video0 \
#         --device=/dev/video1:/dev/video1 \
#         --network host \
#         --volume=/home/pirate/docker-camera/log:/var/log \
#         docker-camera/motion && \
docker run -dit \
         --restart always \
         --network host \
         --volume=/home/pirate/docker-camera/log:/var/log \
         docker-camera/java && \
docker run -dit \
        --restart always \
        --network host \
        --name camera-front \
        docker-camera/front && \
systemctl start commander
