version: "2"
services:
  docker-motion:
    image: docker-camera/motion:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    #volumes:
    #  - "/home/pirate/motion/y:/y"